### ISSUE TITLE
Issue with me :(

### ISSUE THREAD

**Issue by Penguinknees1** [brokenmass/Fancontrol.NzxtKraken#1]
Okay first of all let me say I don't know what I am doing completely. But I have 2 Kraken X3 AIOs in my pc and really need this plugin lol. If someone could inform me on the proper way to install this plugin I would be very thankful. I have been trying to research it for a while and am now pretty lost :'(.

**Comment by brokenmass** [comment]
HI @Penguinknees1 , download this file : https://github.com/brokenmass/Fancontrol.NzxtKraken/releases/download/v1.2.0/FanControl.NzxtKraken.dll and save it in `Plugins` folder of you fancontrol installation.

**Comment by Penguinknees1** [comment]
thank you very much!
