### ISSUE TITLE
Lighting support

### ISSUE THREAD

**Issue by seanwlk** [brokenmass/Fancontrol.NzxtKraken#5]
Hi, is there any way to add support for the Kraken LCD? I really hate NZXT CAM and finally handled to fully migrate to a single app for all the fans, only annoyance left is the LCD that does not disaply the stats nor a simple GIF unless the CAM software is opened

**Comment by brokenmass** [comment]
Hi @seanwlk , yes I wrote something that works very well with signalrgb. 

https://github.com/brokenmass/AIOLCDUnchained

Give it a look. 

I’m actually working on the next improved version so stay tuned
