### ISSUE TITLE
Failed to load plugin FanControl.NzxtKraken.dll

### ISSUE THREAD

**Issue by all-hail-the-omnissiah** [brokenmass/Fancontrol.NzxtKraken#6]
Hey i get this error when starting FanControl after installing the plugin. Any idea what to do ?

![NaDoBU3rw8](https://github.com/brokenmass/Fancontrol.NzxtKraken/assets/108821472/3cd489ee-3b4f-49b9-bb69-421b9b7dc775)

**Comment by brokenmass** [comment]
@Dreadwolf91 my changes have been integrated upstream in librehardwaremonitor so this plugin is no longer needed. Feel free to delete it and ensure you are using a recent version of fancontrol
